# docker-compose.yml
version: "3.3"
services:
    mongodb:
        build: ./mongodb
        hostname: mongodb
        ports:
          - 27017:27017
        volumes:
         - ./c1mysense:/c1mysense
